services:
  - type: web
    name: interviewmaster-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        value: prajyuthsaicheruku@gmail.com
      - key: BREVO_SENDER_NAME
        value: Interview Master
